spring:
    datasource:
        url: "jdbc:postgresql://${RDS_HOSTNAME:localhost}:${RDS_PORT:5432}/ramen_order"
        username: "${RDS_USERNAME:meetings}"
        password: "${RDS_PASSWORD:meetings}"
